artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/SiddharthKarmokar/codeforces-dataset.git
  local_data_file: artifacts/data_ingestion/data
  unzip_dir: artifacts/data_ingestion/raw
  contests_dir: artifacts/data_ingestion/raw/contests
  authors_file: artifacts/data_ingestion/authors.csv 